# Generated by Django 5.1.3 on 2024-11-29 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='points',
        ),
    ]
